### ISSUE TITLE
In demo/techfest, the endpoint of personalizer

### ISSUE THREAD

**Issue by jojohung860815** [Azure-Samples/cognitive-services-personalizer-samples#13]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
when running the application of techfest

### Any log messages given by the failure
>
401 Access Denied

### OS and Version?
> Windows 10

### Mention any other details that might be useful
So the original endpoint url to personalizer api in this sample code is "https://westus2.api.cognitive.microsoft.com/personalization/v1.0/rank".
But the error occurred. It worked when the endpoint url be changed to "https://westus2.api.cognitive.microsoft.com/personalizer/v1.0/rank".
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by edjez** [comment]
#in-progress

**Comment by edjez** [comment]
Correct, apologies!
It is a wrong (older) endpoint - and probably need to scrub that sample again for leftovers from our Private Preview. 
We'll file a task to review it end to end, in the meantime please use endpoints as directed in the docs and as it shows in the Azure Portal.
Thanks @jojohung860815 for taking the time to report this!
