### ISSUE TITLE
Nuget source doesn't exist

### ISSUE THREAD

**Issue by srozga** [Azure-Samples/cognitive-services-personalizer-samples#14]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I'm trying to run the ChatbotExample and can't build it because NuGet.Config is pointing to ../../nuget which doesn't exist.

### Any log messages given by the failure
> /Users/srozga/Desktop/cognitive-services-personalizer-samples/samples/ChatbotExample/LuisBot.csproj : error NU1101: Unable to find package Microsoft.Azure.CognitiveServices.Personalization. No packages exist with this id in source(s): nuget.org

### Expected/desired behavior
> Should work. 

### OS and Version?
> macOS Mojave

### Versions
> dotnet sdk 2.2.300

Thanks!
-s

**Comment by edjez** [comment]
Thanks @srozga! We are fixing the nuget references- in the meantime please [find it here](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Personalizer/0.8.0-preview)

You can also find it in nuget.org feed in VSCode and Visual Studio - remember to check the pre-release checkbox so it appears.
