### ISSUE TITLE
Comment for instantiating client has wrong service

### ISSUE THREAD

**Issue by bbentley19** [Azure-Samples/cognitive-services-personalizer-samples#33]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>Comment says "# Instantiate a LUIS client". This should be say a Personalizer client

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by diberry** [comment]
@bbentley19 - thanks for reporting that - I have a fix in a PR

**Comment by diberry** [comment]
This is fixed. #34

**Comment by edjez** [comment]
👍
