### ISSUE TITLE
The Chatbot  Has Errors In Connecting to LUIS Getting a “ Gone” Result! 

### ISSUE THREAD

**Issue by soniaang** [Azure-Samples/cognitive-services-personalizer-samples#40]
I am Getting this Error when connecting to LUIS 
https://github.com/microsoft/botframework-sdk/issues/5371

From: Sonia Ang 
Sent: Sunday, October 20, 2019 1:23 PM
To: Dina Berry <Dina.Berry@microsoft.com>; Chenxi Zhao <Chenxi.Zhao@microsoft.com>; Edward Jezierski <edjez@microsoft.com>
Subject: RE: Amy clue on personalization example " Coffee bot " 

Gone means  it was not published – but it is .
IT means it also cant reach the Luis keys and app id etc.
IT was able t do the  intro dialogue  but has not reached luis part where it BOMBS.

See this stack opverflow but not sure if  this is related
It is supposed to work  by merely running in it visual studio for testing!! 
I don’t need to deploy  this
https://github.com/microsoft/botframework-sdk/issues/5371

This is V4 bot FWK but it still has the bot file present. But it did s in the literature   bot file is STILL supported

From: Dina Berry <Dina.Berry@microsoft.com> 
Sent: Sunday, October 20, 2019 1:17 PM
To: Sonia Ang <sonan@microsoft.com>; Chenxi Zhao <Chenxi.Zhao@microsoft.com>; Edward Jezierski <edjez@microsoft.com>
Subject: RE: Amy clue on personalization example " Coffee bot " 

I’m unfamiliar with this sample in detail. 

What version of the LUIS SDK are you using? Does the same query work from a cURL command? 

@Chenxi Zhao @Edward Jezierski – thoughts? 

From: Sonia Ang <sonan@microsoft.com> 
Sent: Sunday, October 20, 2019 9:31 AM
To: Dina Berry <Dina.Berry@microsoft.com>
Subject: Amy clue on personalization example " Coffee bot " 

Hello Dina 

I am working on the Personalization Chatbot example and I am getting this error from Luis.
I followed all the instructions in the document 

What is the cause of this – does Luis need the latest release to support RL? There is a preview there I see like V6 ?

> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by EricDahlvang** [comment]
This can be closed.  Solution was to publish to production.

**Comment by homezcx** [comment]
@EricDahlvang  Thanks for confirming. I am going to close it.
