### ISSUE TITLE
KeyError: 'rewardActionId'

### ISSUE THREAD

**Issue by search4mahesh** [Azure-Samples/cognitive-services-personalizer-samples#46]
Hi,

While running personalizer.ipyb notebook, got following error.

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-13-6de181a5a6e6> in <module>
      8 
      9 # main iterations
---> 10 [count, rewards] = iterations(num_requests, lastModCheck, jsonTemplate)

<ipython-input-12-e51ca79911fa> in iterations(n, modelCheck, jsonFormat)
     41 
     42         # compare personalization service recommendation with the simulated data to generate a reward value
---> 43         prediction = json.dumps(response.json()["rewardActionId"]).replace('"','')
     44         reward = get_reward_from_simulated_data(name, weather, timeofday, prediction)
     45 

KeyError: 'rewardActionId'

Please suggest.
Thanks
Mahesh

**Comment by edjez** [comment]
Thanks for the heads up, we will look into it.

**Comment by edjez** [comment]
@search4mahesh were you able to find the rewardActionId in the Rank response?
@tyclintw  - can we issue a fix to the notebook?

**Comment by edjez** [comment]
Tried again and couldn't reproduce, thanks for raising it!
