### ISSUE TITLE
Offline evaluation is not showing optimum policy or anything

### ISSUE THREAD

**Issue by search4mahesh** [Azure-Samples/cognitive-services-personalizer-samples#47]
Hi,

Thanks for amazing Personalization service.
I am trying out Personalizer.ipynb , ecerything worked well but Offline evaluation is not showing anything when date range is given. I think it is supposed to show optimum policy.

Please suggest if I am missing something.

Thanks
Mahesh

**Comment by search4mahesh** [comment]
Looks like there is bug in Start date and end date 
I am giving start date and end date as 1/10/2020 but once it is saved it shows as 1/9/2020.

Thanks
Mahesh

**Comment by edjez** [comment]
Thanks, we are looking into how to make these things not surprising, especially when running the sample that makes a lot of things happen in a short time window. Also, the internal times are stored in GMT, and it may cause confusion.
