### ISSUE TITLE
 Can I relate or abstract the intent based on the underlying question. i.e. a question for a 1 word response would need the context of the question to be useful. 

### ISSUE THREAD

**Issue by xtianus79** [Azure-Samples/cognitive-services-personalizer-samples#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Expected/desired behavior
>
But, I still have that burning question. Can I relate or abstract the intent based on the question. This is important to conversation with the client because again, there could be multiple questions that would have a response of 1 word answers... What is color car are you looking for: black.  What color interior: black.  How can I know the intent for each of those without basing it on the underlying question? In practice, how would this be accomplished? 

I am asking this because the more complex the question i.e. form style questioning the more danger there is to one word answers that have a meaning in context to the question.  

Can you tell me this is possible?  I want to gain the intent from the context of the question.  

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by edjez** [comment]
Thanks @xtianus79 .
What sort of scenario/context does your question apply to?
Could you provide one example of what is the interaction you imagine?

 It sounds like you are trying to disambiguate intent. In that case, each possible intent would be an Action for Personalizer, and you'd have to have features for each, as well as features about the original utterance + additional context, in the Context json. 


 But you would not send the whole original utterance to Personalizer (ie. it won't learn a natural language model all of it's own)

**Comment by edjez** [comment]
Closing as one-off question
