### ISSUE TITLE
'See it in Action' Link doesn't work

### ISSUE THREAD

**Issue by BelRarr** [Azure-Samples/cognitive-services-personalizer-samples#71]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> 1. Go to the readme.md file 
2. go to section 'Demo Websites & Apps'
3. click on the 'See it in action!' link
4. you'll be redirected to 'https://personalizationdemo.azurewebsites.net/' which returns an error

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 11

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by sudosean** [comment]
+1
