### ISSUE TITLE
There are dependencies missing for the chat bot example via the bot samples repo regarding LUIS-Reminders.json

### ISSUE THREAD

**Issue by xtianus79** [Azure-Samples/cognitive-services-personalizer-samples#8]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [x ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
When following the installation instructions for the chatbot example there are missing dependencies in the bot samples repo. Specifically the LUIS-Reminder.json. 

> Click on the Choose File and select LUIS-Reminders.json from the botbuilder-samples/samples/csharp_dotnetcore/12.nlp-with-luis/CognitiveModels folder.

### Any log messages given by the failure
>

### Expected/desired behavior
>
The example to work 

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by edjez** [comment]
@xtianus79 thanks for the report we are adressing it

**Comment by homezcx** [comment]
@xtianus79 @edjez Please check this document update: https://github.com/Azure-Samples/cognitive-services-personalizer-samples/pull/12

**Comment by edjez** [comment]
Fixes in by @homezcx
