### ISSUE TITLE
Dependencies won't load to into this application and it fails at runtime. 

### ISSUE THREAD

**Issue by xtianus79** [Azure-Samples/cognitive-services-personalizer-samples#9]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>
trying to run the application

### Any log messages given by the failure
>
missing nuget package references. Even when trying to restore them in via VS 2019 it won't work. neither with 2017

### Expected/desired behavior
> to work

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
> Windows 10, visual studio 2019 and 2017

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by edjez** [comment]
@xtianus79 are you still having the issue? We did have a time window where the nuget hadn't published on nuget.org. Apologies for the inconvenience.
